name: Test Azure AI NLP

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file for testing
      run: |
        echo "AI_SERVICE_ENDPOINT=fake_endpoint" >> .env
        echo "AI_SERVICE_KEY=fake_key" >> .env

    - name: Check syntax for text-analysis.py
      run: |
        python -m py_compile AzureAI/Language/text-analysis.py

    # Skip actual execution due to API keys
    # - name: Test text-analysis.py (mocked)
    #   run: |
    #     # Would need real API keys and mocked responses

    - name: Test imports
      run: |
        python -c "from dotenv import load_dotenv; print('dotenv import successful')"
        python -c "from azure.core.credentials import AzureKeyCredential; print('Azure imports successful')"